#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: John Hotstone

# Name of the author
author: John Hotstone

# Short bio or description (displayed in the header)
description: A blog about everything that matters ;)

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: john.hotstone@gmail.com
  facebook:
  flickr:
  github: john-hotstone/john-hotstone.github.io
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter:
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:
  mastodon: # <your-mastodon-instance>/@<your-user-name> eg. fosstodon.org/@username

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-Y20S0JYJWQ

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: https://john-hotstone.de/
enforce_ssl: https://john-hotstone.de/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: "/reverie"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

title: John Hotstone

# The release of Jekyll Now that you're using
version: v3.10.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

cloudinary_project: "dc0ncqsdx" # Cloudinary project for remote image includes
cloudinary_scaling_sizes: [320,640,960,1280,1600] # Default sizes for scaling images
cloudinary_sizes_attribute: "(min-width: 50rem) 50rem, 100vw" # Default sizes attribute for image rendering